kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: generic-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeName: generic-pv
  resources:
    requests:
      storage: 1Gi
