kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: sample-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeName: sample-pv
  resources:
    requests:
      storage: 1Gi
