kind: PersistentVolume
apiVersion: v1
metadata:
  name: getresult-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kubegene-getresult
    type: DirectoryOrCreate
